POST http://localhost:5000/api/meeting/add
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AYWRtaW4uY29tIiwiaWF0IjoxNTc4MTY5NzA4fQ.pI2sJM--5FN640kucOKK6yzHXweQidB42jxTkTbuBFY

{
    "professional":"admin@admin.com",
    "client": "5e10f5deb1e4c31d7c1daf86",
    "description": "Igiene dentale... boh",
    "meetingDate": "2020-01-04",
    "sendTo": {
        "whatsapp": true,
        "email": true,
        "instagram": true,
        "facebook": true,
        "sms": true
    },
    "reminder": [
        {
            "date": "2020-02-11",
            "executed": false,
            "text": "Dopo una settimana... reminder!"
        },
        {
            "date": "2020-03-04",
            "executed": false,
            "text": "Dopo un mese... reminder!"
        },
        {
            "date": "2021-02-04",
            "executed": false,
            "text": "Dopo un anno... reminder!"
        }
    ]
}

###

POST http://localhost:5000/api/meeting/add
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AYWRtaW4uY29tIiwiaWF0IjoxNTc4MTY5NzA4fQ.pI2sJM--5FN640kucOKK6yzHXweQidB42jxTkTbuBFY

{
    "professional":"admin@admin.com",
    "client": "5e10f5deb1e4c31d7c1daf86",
    "description": "Igiene dentale... boh",
    "meetingDate": "2020-01-04",
    "sendTo": {
        "whatsapp": true,
        "email": true,
        "instagram": true,
        "facebook": true,
        "sms": true
    },
    "reminder": [
        {
            "date": "2020-01-4",
            "executed": false,
            "text": "Reminder oggi!"
        }
    ]
}


###
GET  http://localhost:5000/api/meeting/getTodayReminders
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AYWRtaW4uY29tIiwiaWF0IjoxNTc4MTY5NzA4fQ.pI2sJM--5FN640kucOKK6yzHXweQidB42jxTkTbuBFY


###
GET  http://localhost:5000/api/meeting/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AYWRtaW4uY29tIiwiaWF0IjoxNTc4MTY5NzA4fQ.pI2sJM--5FN640kucOKK6yzHXweQidB42jxTkTbuBFY

###
GET  http://localhost:5000/api/user/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AYWRtaW4uY29tIiwiaWF0IjoxNTc4MTY5NzA4fQ.pI2sJM--5FN640kucOKK6yzHXweQidB42jxTkTbuBFY
