POST http://localhost:5000/api/sender/email/send
content-type: application/json

{
    "email": "",
    "password": "",
    "toEmail": "",
    "subject": "Reminder da",
    "text": "Ziata prena!"
}

###
GET  http://localhost:5000/api/sender/whatsapp/test
content-type: application/json


###
POST http://localhost:5000/api/sender/facebook/send
content-type: application/json

{
    "email": "",
    "password": "",
    "contactId": 123,
    "msg": "Holaaa (messaggio di prova)"
}


###

POST http://localhost:5000/api/sender/whatsapp/send
content-type: application/json

{
    "instance": "",
    "chatId": "",
    "msg": "Ciaoooo"
}
